/* Generated from web/index.html by tools/embed.sh -- edit the HTML, not this. */
#include <stddef.h>

/* C99 only promises 4095 bytes of string literal; every compiler this
 * project builds with takes far more, and the alternative is a byte array
 * five times the size. */
#pragma GCC diagnostic ignored "-Woverlength-strings"

const char WEBPAGE[] =
    "<!doctype html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    "<meta charset=\"utf-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1,maximum-scale=8\">\n"
    "<meta name=\"theme-color\" content=\"#0e0e12\">\n"
    "<title>vtt</title>\n"
    "<style>\n"
    "html,body{margin:0;background:#0e0e12;color:#d8d8e0;height:100%;overflow:hidden;font:12px/1.4 monospace;-webkit-user-select:none;user-select:none}\n"
    "body{display:flex;align-items:center;justify-content:center}\n"
    "#c{display:block;image-rendering:pixelated;touch-action:pinch-zoom}\n"
    "#s{position:fixed;left:0;bottom:0;padding:2px 6px;background:rgba(14,14,18,.85);color:#60647a;font:11px monospace;pointer-events:none}\n"
    "#s b{color:#8ac8ff;font-weight:normal}\n"
    "</style>\n"
    "</head>\n"
    "<body>\n"
    "<canvas id=\"c\"></canvas>\n"
    "<div id=\"s\">connecting…</div>\n"
    "<script>\n"
    "'use strict';\n"
    "/* vtt remote view. The GM's terminal, drawn the way a terminal draws it:\n"
    " * glyphs rasterised once into an atlas, a pixel framebuffer, and one\n"
    " * putImageData of what changed. Nothing is allocated per frame. */\n"
    "const cv=document.getElementById('c'),st=document.getElementById('s');\n"
    "const ctx=cv.getContext('2d',{alpha:false});\n"
    "let cols=0,rows=0,gl=null,fg=null,bg=null,at=null;        // the cell buffer\n"
    "const pal=new Uint32Array(256);                            // 0xRRGGBB by index\n"
    "let cw=8,ch=16,fpx=13,scale=1;                             // cell size in device px\n"
    "let img=null,px=null;                                      // framebuffer (ImageData, Uint32 view)\n"
    "/* The copy loop, in WebAssembly: tools/blit_wasm.py assembles it by hand.\n"
    " * w(dst, ptrs, n, rows, stride) copies n tiles into a row of the framebuffer,\n"
    " * each listed in ptrs as (byte offset, row bytes). Without it, the same in JS. */\n"
    "const WASM='AGFzbQEAAAABCQFgBX9/f39/AAIIAQFlAW0CAAEDAgEABwUBAXcAAAqQAQGNAQEHfwJAA0AgBSACTw0BIAEgBUEDdGoiCigCACEHIAooAgQhCCAAIQlBACEGAkADQCAGIANPDQFBACELAkADQCALIAhPDQEgCSALaiAHIAtqKQMANwMAIAtBCGohCwwACwsgCSAEaiEJIAcgCGohByAGQQFqIQYMAAsLIAAgCGohACAFQQFqIQUMAAsLCw==';\n"
    "const wmod=typeof WebAssembly!=='undefined'?new WebAssembly.Module(Uint8Array.from(atob(WASM),c=>c.charCodeAt(0))):null;\n"
    "let mem=null,wblit=null,tilesAt=0,tilesEnd=0,tnext=0,ptrsAt=0,ptrs=null,tu32=null;\n"
    "let rd=null,rx0=null,rx1=null,dirtyAll=false;               // dirty span per row, in cells\n"
    "let ms=0,frames=0,ws=null,retry=null;\n"
    "\n"
    "/* ---- glyph atlas: alpha masks, keyed by glyph and bold, made on demand */\n"
    "const atlas=new Map();\n"
    "const gcv=document.createElement('canvas'),gctx=gcv.getContext('2d',{willReadFrequently:true});\n"
    "function mask(g,bold,wide){\n"
    "  const key=g|(bold?1<<21:0)|(wide?1<<22:0);\n"
    "  let m=atlas.get(key);\n"
    "  if(m)return m;\n"
    "  const w=wide?cw*2:cw;\n"
    "  gcv.width=w;gcv.height=ch;\n"
    "  gctx.clearRect(0,0,w,ch);\n"
    "  gctx.fillStyle='#fff';\n"
    "  gctx.font=(bold?'bold ':'')+fpx+'px monospace';\n"
    "  gctx.textBaseline='middle';\n"
    "  gctx.fillText(String.fromCharCode(g),0,ch/2);\n"
    "  const d=gctx.getImageData(0,0,w,ch).data,a=new Uint8Array(w*ch);\n"
    "  for(let i=0,j=3;i<a.length;i++,j+=4)a[i]=d[j];\n"
    "  m={a,w};atlas.set(key,m);\n"
    "  return m;\n"
    "}\n"
    "\n"
    "/* ---- tiles: a glyph in its colours, rendered once, then copied by the row.\n"
    " * The blend runs once per distinct (glyph, colours, attributes), which a\n"
    " * frame has a few hundred of; every cell after that is native row copies. */\n"
    "/* Two levels, so every key is a small integer: the glyph indexes an array,\n"
    " * the colours and attributes key a map beneath it. */\n"
    "const tiles=new Array(65536);let ntiles=0;\n"
    "function tile(g,f,b,a,wide){\n"
    "  let byc=tiles[g];\n"
    "  if(!byc)byc=tiles[g]=new Map();\n"
    "  const key=(a<<17|f<<9|b<<1|(wide?1:0));\n"
    "  let t=byc.get(key);\n"
    "  if(t)return t;\n"
    "  if(++ntiles>4096)clearTiles();\n"
    "  let fc=pal[f],bc=pal[b];\n"
    "  if(a&8){const q=fc;fc=bc;bc=q}                              // reverse\n"
    "  if(a&2)fc=((fc>>1)&0x7f7f7f)+((bc>>1)&0x7f7f7f);            // dim: halfway to the background\n"
    "  const m=mask(g,(a&1)!==0,wide),w=m.w,ma=m.a;\n"
    "  const fr=fc>>16&255,fgn=fc>>8&255,fb=fc&255,br=bc>>16&255,bgn=bc>>8&255,bb=bc&255;\n"
    "  const pixF=0xff000000|fb<<16|fgn<<8|fr,pixB=0xff000000|bb<<16|bgn<<8|br;\n"
    "  const need=w*ch;\n"
    "  if(tnext+need*4>tilesEnd){clearTiles();}\n"
    "  const off=tnext;tnext+=need*4;\n"
    "  const buf=tu32.subarray(off>>2,(off>>2)+need);\n"
    "  for(let k=0;k<buf.length;k++){\n"
    "    const al=ma[k];\n"
    "    if(al===0)buf[k]=pixB;\n"
    "    else if(al===255)buf[k]=pixF;\n"
    "    else{const ia=255-al;\n"
    "      buf[k]=0xff000000|((bb*ia+fb*al)/255|0)<<16|((bgn*ia+fgn*al)/255|0)<<8|((br*ia+fr*al)/255|0)}\n"
    "  }\n"
    "  if(a&4)for(let c=0;c<w;c++)buf[(ch-1)*w+c]=pixF;            // underline\n"
    "  t={off,wb:w*4};byc.set(key,t);\n"
    "  return t;\n"
    "}\n"
    "function clearTiles(){tiles.fill(undefined);ntiles=0;tnext=tilesAt;dirtyAll=true}\n"
    "\n"
    "/* ---- a row's dirty span into the framebuffer: list the tiles, one call */\n"
    "function blitRow(y,x0,x1){\n"
    "  let n=0;\n"
    "  for(let x=x0;x<=x1;x++){\n"
    "    const i=y*cols+x,g=gl[i];\n"
    "    if(g===0)continue;                                     // second half of a wide glyph\n"
    "    const wide=g>0x2E7F&&g<0xA4D0&&x+1<cols&&gl[i+1]===0;\n"
    "    const t=tile(g,fg[i],bg[i],at[i],wide);\n"
    "    ptrs[2*n]=t.off;ptrs[2*n+1]=t.wb;n++;\n"
    "  }\n"
    "  /* x0 may be the blank half of a wide glyph; its tile is one cell back and\n"
    "   * was listed by the caller widening the span. Cells are laid down in\n"
    "   * order, so the destination is x0's, or one cell left of it. */\n"
    "  const start=(y*ch*cols+x0)*cw*4;\n"
    "  if(wblit)wblit(start,ptrsAt,n,ch,cols*cw*4);\n"
    "  else{let d=start>>2;for(let k=0;k<n;k++){const off=ptrs[2*k]>>2,w=ptrs[2*k+1]>>2;let o=d;for(let r=0;r<ch;r++,o+=cols*cw)px.set(tu32.subarray(off+r*w,off+(r+1)*w),o);d+=w}}\n"
    "}\n"
    "\n"
    "/* ---- present the dirty rectangle, once per animation frame */\n"
    "/* An animation frame when the browser will give one, a timer when it will\n"
    " * not: an occluded window gets no animation frames at all. */\n"
    "let raf=0,tmo=0;\n"
    "function present(){\n"
    "  if(raf)cancelAnimationFrame(raf);if(tmo)clearTimeout(tmo);raf=tmo=0;\n"
    "  if(!img)return;\n"
    "  const t0=performance.now();\n"
    "  if(dirtyAll){for(let y=0;y<rows;y++){rd[y]=1;rx0[y]=0;rx1[y]=cols-1}dirtyAll=false}\n"
    "  /* Blit the dirty cells, then push pixels: a few rows go one by one, more\n"
    "   * than that go as one box, since each push is a native copy with a fixed\n"
    "   * cost on top. */\n"
    "  let cells=0,nrows=0,by0=rows,by1=-1,bx0=cols,bx1=-1;\n"
    "  for(let y=0;y<rows;y++){\n"
    "    if(!rd[y])continue;\n"
    "    const x0=rx0[y],x1=rx1[y];\n"
    "    blitRow(y,x0,x1);\n"
    "    cells+=x1-x0+1;nrows++;\n"
    "    if(y<by0)by0=y;if(y>by1)by1=y;if(x0<bx0)bx0=x0;if(x1>bx1)bx1=x1;\n"
    "  }\n"
    "  if(nrows>4)ctx.putImageData(img,0,0,bx0*cw,by0*ch,(bx1-bx0+1)*cw,(by1-by0+1)*ch);\n"
    "  for(let y=0;y<rows;y++){\n"
    "    if(!rd[y])continue;\n"
    "    if(nrows<=4)ctx.putImageData(img,0,0,rx0[y]*cw,y*ch,(rx1[y]-rx0[y]+1)*cw,ch);\n"
    "    rd[y]=0;rx0[y]=1e9;rx1[y]=-1;\n"
    "  }\n"
    "  ms=performance.now()-t0;frames++;last=cells;\n"
    "  status();\n"
    "}\n"
    "function schedule(){if(!raf){raf=requestAnimationFrame(present);tmo=setTimeout(present,50)}}\n"
    "let last=0;\n"
    "function touch(x0,y,x1){if(x0<rx0[y])rx0[y]=x0;if(x1>rx1[y])rx1[y]=x1;rd[y]=1;schedule()}\n"
    "\n"
    "/* ---- sizing: fit the columns to the viewport, crisp at the zoom in force */\n"
    "function layout(){\n"
    "  if(!cols)return;\n"
    "  const vv=window.visualViewport,z=vv?vv.scale:1,dpr=window.devicePixelRatio||1;\n"
    "  scale=dpr*z;\n"
    "  /* The whole frame on screen: as wide as the width allows, or as the\n"
    "   * height does, whichever bites first. A cell is twice as tall as wide. */\n"
    "  cw=Math.max(4,Math.min(Math.floor(window.innerWidth*dpr/cols),Math.floor(window.innerHeight*dpr/(rows*2))))&~1;\n"
    "  fpx=Math.round(cw*1.7);ch=cw*2;\n"
    "  cv.width=cols*cw;cv.height=rows*ch;\n"
    "  cv.style.width=(cv.width/dpr)+'px';cv.style.height=(cv.height/dpr)+'px';\n"
    "  /* One block of memory for everything: the framebuffer, the tile list for\n"
    "   * a row, and an arena of rendered tiles, sized for a few thousand. */\n"
    "  const fbBytes=cv.width*cv.height*4,arena=Math.min(4096*cw*ch*4,8<<20);\n"
    "  ptrsAt=fbBytes;tilesAt=fbBytes+cols*8;tilesEnd=tilesAt+arena;\n"
    "  const pages=Math.ceil(tilesEnd/65536)+1;\n"
    "  let buf;\n"
    "  if(wmod){mem=new WebAssembly.Memory({initial:pages});wblit=new WebAssembly.Instance(wmod,{e:{m:mem}}).exports.w;buf=mem.buffer}\n"
    "  else buf=new ArrayBuffer(pages*65536);\n"
    "  img=new ImageData(new Uint8ClampedArray(buf,0,fbBytes),cv.width,cv.height);\n"
    "  px=new Uint32Array(buf,0,fbBytes>>2);\n"
    "  ptrs=new Int32Array(buf,ptrsAt,cols*2);\n"
    "  tu32=new Uint32Array(buf);\n"
    "  atlas.clear();clearTiles();\n"
    "  schedule();\n"
    "}\n"
    "let lz=0;\n"
    "addEventListener('resize',layout);\n"
    "if(window.visualViewport)window.visualViewport.addEventListener('resize',()=>{clearTimeout(lz);lz=setTimeout(layout,150)});\n"
    "\n"
    "/* ---- the wire: records, little-endian, no text */\n"
    "function feed(u8){\n"
    "  const dv=new DataView(u8.buffer,u8.byteOffset,u8.byteLength);\n"
    "  let p=0;const n=u8.byteLength;\n"
    "  while(p<n){\n"
    "    const t=u8[p];\n"
    "    if(t===0x46){                                          // 'F' w h\n"
    "      const w=dv.getUint16(p+1,true),h=dv.getUint16(p+3,true);p+=5;\n"
    "      if(w!==cols||h!==rows){cols=w;rows=h;gl=new Uint16Array(w*h);fg=new Uint8Array(w*h);bg=new Uint8Array(w*h);at=new Uint8Array(w*h);\n"
    "        rd=new Uint8Array(h);rx0=new Int32Array(h).fill(1e9);rx1=new Int32Array(h).fill(-1);layout()}\n"
    "      dirtyAll=true;\n"
    "    }else if(t===0x50){pal[u8[p+1]]=u8[p+2]<<16|u8[p+3]<<8|u8[p+4];p+=5;clearTiles();dirtyAll=true}   // 'P'\n"
    "    else if(t===0x52){                                     // 'R' x y n fg bg attr, glyphs\n"
    "      const x=dv.getUint16(p+1,true),y=dv.getUint16(p+3,true),k=dv.getUint16(p+5,true);\n"
    "      const f=u8[p+7],b=u8[p+8],a=u8[p+9];p+=10;\n"
    "      if(y<rows){let i=y*cols+x;\n"
    "        for(let j=0;j<k&&x+j<cols;j++,i++){gl[i]=dv.getUint16(p+2*j,true);fg[i]=f;bg[i]=b;at[i]=a}\n"
    "        touch(Math.max(0,x-1),y,Math.min(cols-1,x+k))}     // a neighbour, for a wide glyph's half\n"
    "      p+=2*k;\n"
    "    }else if(t===0x45){p++;schedule()}                     // 'E': present\n"
    "    else if(t===0x5a){p++}                                 // 'Z': keep-alive\n"
    "    else break;\n"
    "  }\n"
    "}\n"
    "\n"
    "/* ---- connection */\n"
    "function status(m){\n"
    "  st.innerHTML=m||('<b>'+cols+'×'+rows+'</b> '+ms.toFixed(2)+' ms · '+last+' cells · '+frames);\n"
    "}\n"
    "function connect(){\n"
    "  const k=new URLSearchParams(location.search).get('k')||'';\n"
    "  ws=new WebSocket((location.protocol==='https:'?'wss://':'ws://')+location.host+'/ws?k='+k);\n"
    "  ws.binaryType='arraybuffer';\n"
    "  ws.onopen=()=>{status('connected');if(navigator.wakeLock)navigator.wakeLock.request('screen').catch(()=>{})};\n"
    "  ws.onmessage=e=>feed(new Uint8Array(e.data));\n"
    "  ws.onclose=()=>{status('disconnected · retrying');retry=setTimeout(connect,2000)};\n"
    "  ws.onerror=()=>ws.close();\n"
    "}\n"
    "connect();\n"
    "</script>\n"
    "</body>\n"
    "</html>\n"
    ;

const size_t WEBPAGE_LEN = sizeof WEBPAGE - 1;
