/* Generated from web/index.html by tools/embed.sh -- edit the HTML, not this. */
#include <stddef.h>

/* C99 only promises 4095 bytes of string literal; every compiler this
 * project builds with takes far more, and the alternative is a byte array
 * five times the size. */
#pragma GCC diagnostic ignored "-Woverlength-strings"

const char WEBPAGE[] =
    "<!doctype html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    "<meta charset=\"utf-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1,maximum-scale=8\">\n"
    "<meta name=\"theme-color\" content=\"#0e0e12\">\n"
    "<title>vtt</title>\n"
    "<style>\n"
    "html,body{margin:0;background:#0e0e12;color:#d8d8e0;height:100%;overflow:hidden;font:12px/1.4 monospace;-webkit-user-select:none;user-select:none}\n"
    "body{display:flex;align-items:center;justify-content:center}\n"
    "#c{display:block;image-rendering:pixelated;touch-action:pinch-zoom}\n"
    "#s{position:fixed;left:0;bottom:0;padding:2px 6px;background:rgba(14,14,18,.85);color:#60647a;font:11px monospace;pointer-events:none}\n"
    "#s b{color:#8ac8ff;font-weight:normal}\n"
    "#h,#hb,#w,#wb,#q,#nb{position:fixed;background:#f3ead6;color:#2a241a;font:17px/1.5 Georgia,serif;border:0;border-radius:6px;box-shadow:0 4px 30px #000}\n"
    "#h,#w,#q{left:50%;top:50%;transform:translate(-50%,-50%);width:min(34em,88vw);max-height:80vh;overflow:auto;box-sizing:border-box;padding:1em 1.3em;user-select:text}\n"
    "[hidden]{display:none!important}\n"
    "#ht,#wt{margin-right:1.5em;font-weight:bold}\n"
    "#hx,#wx{position:absolute;right:.3em;top:0;border:0;background:none;font:28px sans-serif}\n"
    "#hp,#wp{white-space:pre-wrap;overflow-wrap:anywhere}\n"
    "#hb,#wb,#nb{padding:.4em 1em}\n"
    "#hb{right:9px;bottom:9px}\n"
    "#wb{right:9px;bottom:3.6em}\n"
    "#nb{left:9px;top:9px;opacity:.8}\n"
    "#w{background:#e6dcf3}\n"
    "#q button,#q input{display:block;width:100%;box-sizing:border-box;margin:.4em 0;font:inherit;padding:.3em}\n"
    "</style>\n"
    "</head>\n"
    "<body>\n"
    "<canvas id=\"c\"></canvas>\n"
    "<div id=\"s\">connecting…</div>\n"
    "<div id=\"h\" hidden><button id=\"hx\" aria-label=\"close\">×</button><div id=\"ht\"></div><p id=\"hp\"></p></div>\n"
    "<button id=\"hb\" hidden>handout</button>\n"
    "<div id=\"w\" hidden><button id=\"wx\" aria-label=\"close\">×</button><div id=\"wt\">to you</div><p id=\"wp\"></p></div>\n"
    "<button id=\"wb\" hidden>whisper</button>\n"
    "<button id=\"nb\">who?</button>\n"
    "<div id=\"q\" hidden><b>Who are you?</b><div id=\"ql\"></div><input id=\"qi\" maxlength=\"24\" placeholder=\"another name\"><button id=\"qo\">that's me</button><button id=\"qw\">just watching</button></div>\n"
    "<script>\n"
    "'use strict';\n"
    "const cv=document.getElementById('c'),st=document.getElementById('s');\n"
    "const ctx=cv.getContext('2d',{alpha:false});\n"
    "let cols=0,rows=0,gl=null,fg=null,bg=null,at=null;        // the cell buffer\n"
    "const pal=new Uint32Array(256);                            // 0xRRGGBB by index\n"
    "let cw=8,ch=16,fpx=13,scale=1;                             // cell size in device px\n"
    "let img=null,px=null;                                      // framebuffer (ImageData, Uint32 view)\n"
    "const WASM='AGFzbQEAAAABCQFgBX9/f39/AAIIAQFlAW0CAAEDAgEABwUBAXcAAAqQAQGNAQEHfwJAA0AgBSACTw0BIAEgBUEDdGoiCigCACEHIAooAgQhCCAAIQlBACEGAkADQCAGIANPDQFBACELAkADQCALIAhPDQEgCSALaiAHIAtqKQMANwMAIAtBCGohCwwACwsgCSAEaiEJIAcgCGohByAGQQFqIQYMAAsLIAAgCGohACAFQQFqIQUMAAsLCw==';\n"
    "const wmod=typeof WebAssembly!=='undefined'?new WebAssembly.Module(Uint8Array.from(atob(WASM),c=>c.charCodeAt(0))):null;\n"
    "let mem=null,wblit=null,tilesAt=0,tilesEnd=0,tnext=0,ptrsAt=0,ptrs=null,tu32=null;\n"
    "let rd=null,rx0=null,rx1=null,dirtyAll=false;               // dirty span per row, in cells\n"
    "let ms=0,frames=0,ws=null,retry=null;\n"
    "const atlas=new Map();\n"
    "const gcv=document.createElement('canvas'),gctx=gcv.getContext('2d',{willReadFrequently:true});\n"
    "function mask(g,bold,wide){\n"
    "  const key=g|(bold?1<<21:0)|(wide?1<<22:0);\n"
    "  let m=atlas.get(key);\n"
    "  if(m)return m;\n"
    "  const w=wide?cw*2:cw;\n"
    "  gcv.width=w;gcv.height=ch;\n"
    "  gctx.clearRect(0,0,w,ch);\n"
    "  gctx.fillStyle='#fff';\n"
    "  gctx.font=(bold?'bold ':'')+fpx+'px monospace';\n"
    "  gctx.textBaseline='middle';\n"
    "  gctx.fillText(String.fromCharCode(g),0,ch/2);\n"
    "  const d=gctx.getImageData(0,0,w,ch).data,a=new Uint8Array(w*ch);\n"
    "  for(let i=0,j=3;i<a.length;i++,j+=4)a[i]=d[j];\n"
    "  m={a,w};atlas.set(key,m);\n"
    "  return m;\n"
    "}\n"
    "const tiles=new Array(65536);let ntiles=0;\n"
    "function tile(g,f,b,a,wide){\n"
    "  let byc=tiles[g];\n"
    "  if(!byc)byc=tiles[g]=new Map();\n"
    "  const key=(a<<17|f<<9|b<<1|(wide?1:0));\n"
    "  let t=byc.get(key);\n"
    "  if(t)return t;\n"
    "  if(++ntiles>4096)clearTiles();\n"
    "  let fc=pal[f],bc=pal[b];\n"
    "  if(a&8){const q=fc;fc=bc;bc=q}                              // reverse\n"
    "  if(a&2)fc=((fc>>1)&0x7f7f7f)+((bc>>1)&0x7f7f7f);            // dim: halfway to the background\n"
    "  const m=mask(g,(a&1)!==0,wide),w=m.w,ma=m.a;\n"
    "  const fr=fc>>16&255,fgn=fc>>8&255,fb=fc&255,br=bc>>16&255,bgn=bc>>8&255,bb=bc&255;\n"
    "  const pixF=0xff000000|fb<<16|fgn<<8|fr,pixB=0xff000000|bb<<16|bgn<<8|br;\n"
    "  const need=w*ch;\n"
    "  if(tnext+need*4>tilesEnd){clearTiles();}\n"
    "  const off=tnext;tnext+=need*4;\n"
    "  const buf=tu32.subarray(off>>2,(off>>2)+need);\n"
    "  for(let k=0;k<buf.length;k++){\n"
    "    const al=ma[k];\n"
    "    if(al===0)buf[k]=pixB;\n"
    "    else if(al===255)buf[k]=pixF;\n"
    "    else{const ia=255-al;\n"
    "      buf[k]=0xff000000|((bb*ia+fb*al)/255|0)<<16|((bgn*ia+fgn*al)/255|0)<<8|((br*ia+fr*al)/255|0)}\n"
    "  }\n"
    "  if(a&4)for(let c=0;c<w;c++)buf[(ch-1)*w+c]=pixF;            // underline\n"
    "  t={off,wb:w*4};byc.set(key,t);\n"
    "  return t;\n"
    "}\n"
    "function clearTiles(){tiles.fill(undefined);ntiles=0;tnext=tilesAt;dirtyAll=true}\n"
    "function blitRow(y,x0,x1){\n"
    "  let n=0;\n"
    "  for(let x=x0;x<=x1;x++){\n"
    "    const i=y*cols+x,g=gl[i];\n"
    "    if(g===0)continue;                                     // second half of a wide glyph\n"
    "    const wide=g>0x2E7F&&g<0xA4D0&&x+1<cols&&gl[i+1]===0;\n"
    "    const t=tile(g,fg[i],bg[i],at[i],wide);\n"
    "    ptrs[2*n]=t.off;ptrs[2*n+1]=t.wb;n++;\n"
    "  }\n"
    "  const start=(y*ch*cols+x0)*cw*4;\n"
    "  if(wblit)wblit(start,ptrsAt,n,ch,cols*cw*4);\n"
    "  else{let d=start>>2;for(let k=0;k<n;k++){const off=ptrs[2*k]>>2,w=ptrs[2*k+1]>>2;let o=d;for(let r=0;r<ch;r++,o+=cols*cw)px.set(tu32.subarray(off+r*w,off+(r+1)*w),o);d+=w}}\n"
    "}\n"
    "let raf=0,tmo=0;\n"
    "function present(){\n"
    "  if(raf)cancelAnimationFrame(raf);if(tmo)clearTimeout(tmo);raf=tmo=0;\n"
    "  if(!img)return;\n"
    "  const t0=performance.now();\n"
    "  if(dirtyAll){for(let y=0;y<rows;y++){rd[y]=1;rx0[y]=0;rx1[y]=cols-1}dirtyAll=false}\n"
    "  let cells=0,nrows=0,by0=rows,by1=-1,bx0=cols,bx1=-1;\n"
    "  for(let y=0;y<rows;y++){\n"
    "    if(!rd[y])continue;\n"
    "    const x0=rx0[y],x1=rx1[y];\n"
    "    blitRow(y,x0,x1);\n"
    "    cells+=x1-x0+1;nrows++;\n"
    "    if(y<by0)by0=y;if(y>by1)by1=y;if(x0<bx0)bx0=x0;if(x1>bx1)bx1=x1;\n"
    "  }\n"
    "  if(nrows>4)ctx.putImageData(img,0,0,bx0*cw,by0*ch,(bx1-bx0+1)*cw,(by1-by0+1)*ch);\n"
    "  for(let y=0;y<rows;y++){\n"
    "    if(!rd[y])continue;\n"
    "    if(nrows<=4)ctx.putImageData(img,0,0,rx0[y]*cw,y*ch,(rx1[y]-rx0[y]+1)*cw,ch);\n"
    "    rd[y]=0;rx0[y]=1e9;rx1[y]=-1;\n"
    "  }\n"
    "  ms=performance.now()-t0;frames++;last=cells;\n"
    "  status();\n"
    "}\n"
    "function schedule(){if(!raf){raf=requestAnimationFrame(present);tmo=setTimeout(present,50)}}\n"
    "let last=0;\n"
    "function touch(x0,y,x1){if(x0<rx0[y])rx0[y]=x0;if(x1>rx1[y])rx1[y]=x1;rd[y]=1;schedule()}\n"
    "function layout(){\n"
    "  if(!cols)return;\n"
    "  const vv=window.visualViewport,z=vv?vv.scale:1,dpr=window.devicePixelRatio||1;\n"
    "  scale=dpr*z;\n"
    "  cw=Math.max(4,Math.min(Math.floor(window.innerWidth*dpr/cols),Math.floor(window.innerHeight*dpr/(rows*2))))&~1;\n"
    "  fpx=Math.round(cw*1.7);ch=cw*2;\n"
    "  cv.width=cols*cw;cv.height=rows*ch;\n"
    "  cv.style.width=(cv.width/dpr)+'px';cv.style.height=(cv.height/dpr)+'px';\n"
    "  const fbBytes=cv.width*cv.height*4,arena=Math.min(4096*cw*ch*4,8<<20);\n"
    "  ptrsAt=fbBytes;tilesAt=fbBytes+cols*8;tilesEnd=tilesAt+arena;\n"
    "  const pages=Math.ceil(tilesEnd/65536)+1;\n"
    "  let buf;\n"
    "  if(wmod){mem=new WebAssembly.Memory({initial:pages});wblit=new WebAssembly.Instance(wmod,{e:{m:mem}}).exports.w;buf=mem.buffer}\n"
    "  else buf=new ArrayBuffer(pages*65536);\n"
    "  img=new ImageData(new Uint8ClampedArray(buf,0,fbBytes),cv.width,cv.height);\n"
    "  px=new Uint32Array(buf,0,fbBytes>>2);\n"
    "  ptrs=new Int32Array(buf,ptrsAt,cols*2);\n"
    "  tu32=new Uint32Array(buf);\n"
    "  atlas.clear();clearTiles();\n"
    "  schedule();\n"
    "}\n"
    "let lz=0;\n"
    "addEventListener('resize',layout);\n"
    "if(window.visualViewport)window.visualViewport.addEventListener('resize',()=>{clearTimeout(lz);lz=setTimeout(layout,150)});\n"
    "function feed(u8){\n"
    "  const dv=new DataView(u8.buffer,u8.byteOffset,u8.byteLength);\n"
    "  let p=0;const n=u8.byteLength;\n"
    "  while(p<n){\n"
    "    const t=u8[p];\n"
    "    if(t===0x46){                                          // 'F' w h\n"
    "      const w=dv.getUint16(p+1,true),h=dv.getUint16(p+3,true);p+=5;\n"
    "      if(w!==cols||h!==rows){cols=w;rows=h;gl=new Uint16Array(w*h);fg=new Uint8Array(w*h);bg=new Uint8Array(w*h);at=new Uint8Array(w*h);\n"
    "        rd=new Uint8Array(h);rx0=new Int32Array(h).fill(1e9);rx1=new Int32Array(h).fill(-1);layout()}\n"
    "      dirtyAll=true;\n"
    "    }else if(t===0x50){pal[u8[p+1]]=u8[p+2]<<16|u8[p+3]<<8|u8[p+4];p+=5;clearTiles();dirtyAll=true}   // 'P'\n"
    "    else if(t===0x52){                                     // 'R' x y n fg bg attr, glyphs\n"
    "      const x=dv.getUint16(p+1,true),y=dv.getUint16(p+3,true),k=dv.getUint16(p+5,true);\n"
    "      const f=u8[p+7],b=u8[p+8],a=u8[p+9];p+=10;\n"
    "      if(y<rows){let i=y*cols+x;\n"
    "        for(let j=0;j<k&&x+j<cols;j++,i++){gl[i]=dv.getUint16(p+2*j,true);fg[i]=f;bg[i]=b;at[i]=a}\n"
    "        touch(Math.max(0,x-1),y,Math.min(cols-1,x+k))}     // a neighbor, for a wide glyph's half\n"
    "      p+=2*k;\n"
    "    }else if(t===0x45){p++;schedule()}                     // 'E': present\n"
    "    else if(t===0x5a){p++}                                 // 'Z': keep-alive\n"
    "    else if(t===0x48||t===0x57||t===0x4e){                 // 'H' handout, 'W' whisper, 'N' names: n text\n"
    "      const k=dv.getUint16(p+1,true),s=dec.decode(u8.subarray(p+3,p+3+k));p+=3+k;\n"
    "      (t===0x48?handout:t===0x57?whisper:names)(s);\n"
    "    }\n"
    "    else break;\n"
    "  }\n"
    "}\n"
    "const E=id=>document.getElementById(id),dec=new TextDecoder(),hd=E('h'),hb=E('hb'),ht=E('ht'),hp=E('hp');\n"
    "let hkey='';\n"
    "function handout(s){\n"
    "  const nl=s.indexOf('\\n');\n"
    "  ht.textContent=nl<0?s:s.slice(0,nl);ht.hidden=!ht.textContent;hp.textContent=nl<0?'':s.slice(nl+1);\n"
    "  if(s!==hkey){hd.hidden=!s;hb.hidden=true;hd.scrollTop=0}\n"
    "  hkey=s;\n"
    "}\n"
    "E('hx').onclick=()=>{hd.hidden=true;hb.hidden=false};\n"
    "hb.onclick=()=>{hd.hidden=false;hb.hidden=true};\n"
    "let me=null,asked=0;try{me=localStorage.getItem('vtt-name')}catch(e){}\n"
    "const nb=E('nb'),q=E('q'),ql=E('ql'),qi=E('qi'),wd=E('w'),wb=E('wb');\n"
    "nb.textContent=me||'who?';\n"
    "function setMe(v){\n"
    "  me=v;try{localStorage.setItem('vtt-name',v)}catch(e){}\n"
    "  q.hidden=true;nb.textContent=v||'who?';\n"
    "  if(ws){ws.onclose=ws.onerror=null;ws.close();clearTimeout(retry);connect()}\n"
    "}\n"
    "function names(s){\n"
    "  ql.textContent='';\n"
    "  for(const v of s?s.split('\\n'):[]){const b=document.createElement('button');b.textContent=v;b.onclick=()=>setMe(v);ql.appendChild(b)}\n"
    "  if(me===null&&!asked){asked=1;q.hidden=false}\n"
    "}\n"
    "nb.onclick=()=>{q.hidden=!q.hidden};\n"
    "E('qo').onclick=()=>{const c=[...qi.value.trim()];while(new TextEncoder().encode(c.join('')).length>24)c.pop();const v=c.join('').trim();if(v)setMe(v)};\n"
    "E('qw').onclick=()=>setMe('');\n"
    "function whisper(s){E('wp').textContent=s;wd.hidden=false;wb.hidden=true;wd.scrollTop=0}\n"
    "E('wx').onclick=()=>{wd.hidden=true;wb.hidden=false};\n"
    "wb.onclick=()=>{wd.hidden=false;wb.hidden=true};\n"
    "function status(m){\n"
    "  st.innerHTML=m||('<b>'+cols+'×'+rows+'</b> '+ms.toFixed(2)+' ms · '+last+' cells · '+frames);\n"
    "}\n"
    "function connect(){\n"
    "  const k=new URLSearchParams(location.search).get('k')||'';\n"
    "  const s=ws=new WebSocket((location.protocol==='https:'?'wss://':'ws://')+location.host+'/ws?k='+k+(me?'&n='+encodeURIComponent(me):''));\n"
    "  s.binaryType='arraybuffer';\n"
    "  s.onopen=()=>{status('connected');if(navigator.wakeLock)navigator.wakeLock.request('screen').catch(()=>{})};\n"
    "  s.onmessage=e=>feed(new Uint8Array(e.data));\n"
    "  s.onclose=()=>{status('disconnected · retrying');retry=setTimeout(connect,2000)};\n"
    "  s.onerror=()=>s.close();\n"
    "}\n"
    "connect();\n"
    "let lastPing=0;\n"
    "cv.addEventListener('click',e=>{\n"
    "  if(!cols||!ws||ws.readyState!==1)return;\n"
    "  const r=cv.getBoundingClientRect();\n"
    "  const x=Math.floor((e.clientX-r.left)/r.width*cols),y=Math.floor((e.clientY-r.top)/r.height*rows);\n"
    "  if(x<0||y<0||x>=cols||y>=rows)return;\n"
    "  const now=Date.now();\n"
    "  if(now-lastPing<1100)return;\n"
    "  lastPing=now;\n"
    "  ws.send('P '+x+' '+y);\n"
    "});\n"
    "</script>\n"
    "</body>\n"
    "</html>\n"
    ;

const size_t WEBPAGE_LEN = sizeof WEBPAGE - 1;
